version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # Логин
      - RABBITMQ_DEFAULT_PASS=guest  # Пароль
    restart: always
