// <auto-generated />
using System;
using BPMSystem.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BPMSystem.Migrations
{
    [DbContext(typeof(BPMContext))]
    partial class BPMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BPMEngine.Models.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedOn")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("text");

                    b.Property<string>("ProcessConfig")
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedOn")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("BPMEngine.Models.Entities.QueryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedOn")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .HasColumnType("text");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepId")
                        .HasColumnType("text");

                    b.Property<long?>("UpdatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedOn")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("QueryConfigs");
                });

            modelBuilder.Entity("BPMEngine.Models.Entities.StateContainerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CreatedOn")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .HasColumnType("text");

                    b.Property<string>("ProcessCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<long?>("UpdatedDate")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UpdatedOn")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("StateContainerConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
